### ISSUE TITLE
生成不了加密文件

### ISSUE THREAD

**Issue by binxiaoxiaobin** [LCF2764/Encrypt-python-code-License-control#7]
使用实例生成不了加密文件

**Comment by LCF2764** [comment]
描述一下你遇到的问题

**Comment by lk1983823** [comment]
Compiling get_time.py because it changed.
[1/1] Cythonizing get_time.py
/home/lk/.pyenv/versions/anaconda3-2020.02/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /media/lk/disk1/lk_git/8_Python/Encrypt-python-code-License-control/Example/get_time.py
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'get_time' extension
creating build/temp.linux-x86_64-3.7
gcc -pthread -B /home/lk/.pyenv/versions/anaconda3-2020.02/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/lk/.pyenv/versions/anaconda3-2020.02/include/python3.7m -c get_time.c -o build/temp.linux-x86_64-3.7/get_time.o
gcc -pthread -shared -B /home/lk/.pyenv/versions/anaconda3-2020.02/compiler_compat -L/home/lk/.pyenv/versions/anaconda3-2020.02/lib -Wl,-rpath=/home/lk/.pyenv/versions/anaconda3-2020.02/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/get_time.o -o /media/lk/disk1/lk_git/8_Python/Encrypt-python-code-License-control/Example/get_time.cpython-37m-x86_64-linux-gnu.so
—————— /media/lk/disk1/lk_git/8_Python/Encrypt-python-code-License-control/Example ——————
['get_time.py.bak', 'get_time.cpython-37m-x86_64-linux-gnu.so', 'setup.py', 'get_time.c', 'build', 'license.lic', 'get_time.py', 'main.py']
Done!
只生成了Encrypt-python-code-License-control/Example/build/temp.linux-x86_64-3.7/get_time.o 文件, 在example文件夹下并没有.c和.so 文件

**Comment by LCF2764** [comment]
使用python2能解决。

**Comment by lk1983823** [comment]
能否增加一个统计次数或者比对时间以后（试用天数），终止的功能？

**Comment by LCF2764** [comment]
> 能否增加一个统计次数或者比对时间以后（试用天数），终止的功能？

感谢你的提议，后期会增加这个功能。
